import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'data.json');
const CACHE = path.join(ROOT, 'cache');

const EMPTY = { agents: [], events: [], beliefs: [], transcripts: [] };

let db = load();

function load() {
  try {
    if (fs.existsSync(DATA)) {
      return { ...EMPTY, ...JSON.parse(fs.readFileSync(DATA, 'utf8')) };
    }
  } catch (e) {
    console.warn('[store] data.json unreadable, starting fresh:', e.message);
  }
  return structuredClone(EMPTY);
}

export function save() {
  fs.writeFileSync(DATA, JSON.stringify(db, null, 2));
}

export function state() { return db; }

export function reset() {
  db = structuredClone(EMPTY);
  save();
  return db;
}

export function id(prefix) {
  return `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
}

/* ---------- agents (NPCs / support reps / whatever the domain is) ---------- */

export function addAgent(a) {
  const agent = {
    id: a.id || id('agent'),
    name: a.name,
    role: a.role || '',
    location: a.location || '',
    persona: a.persona || '',
    // Who this agent talks to. Drives propagation routes.
    ties: a.ties || [],
    // Hard epistemic ceiling. Grok is told it may never assign these.
    forbidden: a.forbidden || [],
  };
  db.agents.push(agent);
  save();
  return agent;
}

export function getAgent(agentId) {
  return db.agents.find((a) => a.id === agentId) || null;
}

export function removeAgent(agentId) {
  db.agents = db.agents.filter((a) => a.id !== agentId);
  db.beliefs = db.beliefs.filter((b) => b.agentId !== agentId);
  save();
}

/* ---------- beliefs (the retrievable, per-agent knowledge) ---------- */

export function addBelief(b) {
  const belief = {
    id: b.id || id('bel'),
    agentId: b.agentId,
    eventId: b.eventId || null,
    content: b.content,
    confidence: typeof b.confidence === 'number' ? b.confidence : 0.8,
    route: b.route || 'baseline',       // how they came to know it
    distortion: b.distortion || 'none', // how wrong it got in transit
    reasoning: b.reasoning || '',       // Grok's justification — shown in UI
    vec: b.vec || null,
    at: b.at || new Date().toISOString(),
  };
  db.beliefs.push(belief);
  save();
  return belief;
}

export function beliefsFor(agentId) {
  return db.beliefs.filter((b) => b.agentId === agentId);
}

export function removeBelief(beliefId) {
  const n = db.beliefs.length;
  db.beliefs = db.beliefs.filter((b) => b.id !== beliefId);
  save();
  return db.beliefs.length < n;
}

/* ---------- events ---------- */

export function addEvent(e) {
  const ev = {
    id: e.id || id('evt'),
    text: e.text,
    location: e.location || '',
    witnesses: e.witnesses || [],
    // 'world' = fired by the village clock. 'interaction' = generated by a
    // player conversation (V2), which feeds back into propagation.
    kind: e.kind || 'world',
    summary: '',
    knownBy: 0,
    at: e.at || new Date().toISOString(),
  };
  db.events.push(ev);
  save();
  return ev;
}

/** Attach the propagation outcome to an event so the news feed can show it. */
export function annotateEvent(eventId, { summary, knownBy }) {
  const ev = db.events.find((x) => x.id === eventId);
  if (!ev) return null;
  if (summary !== undefined) ev.summary = summary;
  if (knownBy !== undefined) ev.knownBy = knownBy;
  save();
  return ev;
}

/** How many pool events have fired — drives the village clock. */
export function worldEventCount() {
  return db.events.filter((e) => e.kind === 'world').length;
}

export function addTranscript(t) {
  db.transcripts.push({ id: id('t'), at: new Date().toISOString(), ...t });
  if (db.transcripts.length > 200) db.transcripts.shift();
  save();
}

/* ---------- propagation cache -------------------------------------------
 * "It works — 40 points. Does it run?" A cached propagation means the demo
 * survives dead venue wifi and a rate limit. Keyed on the event text.
 * ------------------------------------------------------------------------ */

function cacheKey(text) {
  let h = 5381;
  for (let i = 0; i < text.length; i++) h = ((h << 5) + h + text.charCodeAt(i)) | 0;
  return `prop_${Math.abs(h).toString(36)}.json`;
}

export function readCache(text) {
  try {
    const p = path.join(CACHE, cacheKey(text));
    if (fs.existsSync(p)) return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch { /* ignore */ }
  return null;
}

export function writeCache(text, payload) {
  try {
    fs.mkdirSync(CACHE, { recursive: true });
    fs.writeFileSync(path.join(CACHE, cacheKey(text)), JSON.stringify(payload, null, 2));
  } catch (e) {
    console.warn('[store] cache write failed:', e.message);
  }
}
